spring:
  application:
    name: consumer-prod
  data:
    redis:
      host: redis-service
      port: 6379
logstash:
  host: logstash-logstash
  port: 5044
rocketmq:
  producer:
    endpoints: rocketmq-proxy:8081
    ssl-enabled: false