# 生产环境配置
forbidden:
  filePath: /forbidden/forbidden.txt
# gRPC 客户端配置
grpc:
  client:
    AiService:
      address: ${grpc-client.ai-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    PostService:
      address: ${grpc-client.post-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    PostHistoryService:
      address: ${grpc-client.post-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    PostChunkVectorService:
      address: ${grpc-client.post-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    DirectoryService:
      address: ${grpc-client.post-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    KnowledgeBaseService:
      address: ${grpc-client.post-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    UserService:
      address: ${grpc-client.user-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    UserLogService:
      address: ${grpc-client.user-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    UserExtraInfoService:
      address: ${grpc-client.user-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    PostCloneService:
      address: ${grpc-client.go-service}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
