spring:
  datasource:
    url: jdbc:postgresql://129.226.208.121:32701/blog?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: 129.226.208.121
      port: 30229
  elasticsearch:
    uris: https://43.163.122.45:30589
logstash:
  host: 43.163.122.45
  port: 30646
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rocketmq:
  producer:
    endpoints: rocketmq-proxy:8081
    ssl-enabled: false