spring:
  datasource:
    url: jdbc:postgresql://my-postgres-postgresql:5432/blog?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: redis-service
      port: 6379
  elasticsearch:
    uris: https://elasticsearch-master:9200
logstash:
  host: logstash-logstash
  port: 5044
rocketmq:
  producer:
    endpoints: rocketmq-proxy:8081
    ssl-enabled: false


grpc:
  client:
    TestService:
      address: 'static://test-svc:9092'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    AiService:
      address: 'static://ai-svc:9092'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true