spring:
  datasource:
    url: jdbc:postgresql://my-postgres-postgresql.default.cluster.local:5432/blog?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: redis-service.default.cluster.local
      port: 6379
  elasticsearch:
    uris: https://elasticsearch-master.default.cluster.local:9200
logstash:
  host: logstash-logstash.default.cluster.local
  port: 5044
grpc:
  client:
    TestService:
      address: 'static://127.0.0.1:9093'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
