# 开发环境配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
forbidden:
  filePath: C:\forbidden\forbidden.txt
logging:
  config: classpath:log4j-spring.xml
  level:
    com.cainsgl: DEBUG
    org.springframework.web.client: DEBUG