spring:
  datasource:
    url: jdbc:postgresql://my-postgres-postgresql:5432/blog?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: redis-service
      port: 6379
  elasticsearch:
    uris: https://elasticsearch-master:9200
logstash:
  host: logstash-logstash
  port: 5044
rocketmq:
  push-consumer:
    endpoints: rocketmq-proxy:8080
  producer:
    endpoints: rocketmq-proxy:8080
    ssl-enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
